<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\HotelSaas.Tenant.Application\HotelSaas.Tenant.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\HotelSaas.BuildingBlocks.Persistence\HotelSaas.BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
  </ItemGroup>

  <PropertyGroup>
  </PropertyGroup>

</Project>
